GET http://localhost:9000/user/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODE5LCJpYXQiOjE2NTM5NzA3MTgsImV4cCI6MTY1NDAxMzkxOH0.GLzUS9aGlJKNyPOmPzUGDgepfVfjycX_bSptDW1-HUM

###
GET http://localhost:9000/admin/cids

###
POST http://localhost:9000/user/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODE5LCJpYXQiOjE2NTM5NzA3MTgsImV4cCI6MTY1NDAxMzkxOH0.GLzUS9aGlJKNyPOmPzUGDgepfVfjycX_bSptDW1-HUM
Content-Type: application/json

{
  "previous": "555555",
  "candidate": "555555",
  "confirmed": "555555"
}
###

POST http://localhost:9000/login
Content-Type: application/json

{
  "name": "admin_kryk",
  "password": "09051945"
}
