GET http://127.0.0.1:3000/psb?QueryType=pay&TransactionId=1234567&Account=101111

###
# POST https://billing.asknet.online:9000/login
# Content-Type: application/json

# {
#   "login": "admin_kryk",
#   "password": "09051945"
# }
